---
title: "03a_main_analysis"
output: github_document
keep_html: TRUE
---

```{r Packages}
if (!require("bigutilsr")) {install.packages("bigutilsr"); require("bigutilsr")}
if (!require("dbscan")) {install.packages("dbscan"); require("dbscan")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("EMAtools")) {install.packages("EMAtools"); require("EMAtools")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("ICS")) {install.packages("ICS"); require("ICS")}
if (!require("ICSOutlier")) {install.packages("ICSOutlier"); require("ICSOutlier")}
if (!require("insight")) {install.packages("insight"); require("insight")}
if (!require("lme4")) {install.packages("lme4"); require("lme4")}
if (!require("lmerTest")) {install.packages("lmerTest"); require("lmerTest")}
if (!require("performance")) {install.packages("performance"); require("performance")}
if (!require("psych")) {install.packages("psych"); require("psych")}
if (!require("pwr")) {install.packages("pwr"); require("pwr")}
if (!require("sjPlot")) {install.packages("sjPlot"); require("sjPlot")}
devtools::install_github("sjPlot/sjstats")
if (!require("sjstats")) {install.packages("sjstats"); require("sjstats")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")}
```

```{r Functions}
# Cohen's d for MLMs 
lme.dscore <- function(mod,data,type){
  if (type == "lme4") {
    mod1 <- lmerTest::lmer(mod, data=data)
    eff <- cbind(summary(mod1)$coefficients[,4], summary(mod1)$coefficients[,3])
  }

  if (type == "nlme") {
    eff = cbind(summary(mod)$tTable[,4], summary(mod)$fixDF$terms)
  }

  colnames(eff) <- c("t","df")
  eff <- as.data.frame(eff)
  eff$d <- (2*eff$t)/sqrt(eff$df)
  eff <- eff[-1,]
  return(eff)
}

# Person means
pmean <- function(ID,var){
  centered <- ave(var, ID, FUN = function(x) mean(x, na.rm = TRUE))
  return(centered)
}

# Person center
pcenter<-function(ID,var){
  centered<- var-ave(var, ID, FUN = function(x) mean(x, na.rm = TRUE))
  return(centered)
}

# power curve
ema.powercurve=function(NumbPart,NumbResp,days,respday,Est_ICC=.05,COL.8="red",COL.5="blue",COL.2="green"){


  if(!missing(days) & !missing(respday)) {
    NumbResp<-days*respday
  } else {
    NumbResp<-NumbResp
  }

  ### initate matricies ####
  eff8a<-NULL;eff2a<-NULL;eff5a<-NULL

  #### functions for power curves ####

  for (PWR in c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.99)){
    eff8<-(sjstats::smpsize_lmm(eff.size = 0.8, power = PWR, sig.level = 0.05, k = NumbPart, icc = Est_ICC,n=NumbResp))
    eff8a<-as.data.frame(rbind(eff8a,eff8$`Subjects per Cluster`))
  }

  for (PWR in c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.99)){
    eff5<-(sjstats::smpsize_lmm(eff.size = 0.5, power = PWR, sig.level = 0.05, k = NumbPart, icc = Est_ICC,n=NumbResp))
    eff5a<-as.data.frame(rbind(eff5a,eff5$`Subjects per Cluster`))
  }


  for (PWR in c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.99)){
    eff2<-(sjstats::smpsize_lmm(eff.size = 0.2, power = PWR, sig.level = 0.05, k = NumbPart, icc = Est_ICC,n=NumbResp))
    eff2a<-as.data.frame(rbind(eff2a,eff2$`Subjects per Cluster`))
  }


  for (Add99 in c(10,20,30,40,50,60,70,75,80,85,90,95,100,105,110,115,120,125,130,140,150,160,170)){
    eff2a<-as.data.frame(rbind(eff2a,(eff2$`Subjects per Cluster`+Add99)))
    eff5a<-as.data.frame(rbind(eff5a,(eff5$`Subjects per Cluster`+Add99)))
    eff8a<-as.data.frame(rbind(eff8a,(eff8$`Subjects per Cluster`+Add99)))
  }

  ### merging curves ###
  power<-rbind(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99,0.99)

  ### creating response rate lines


  NumbRespColumn<-cbind(rep(c((NumbResp*.50),(NumbResp*.75),(NumbResp)),each=34))

  LabResp<-cbind(rep(c("50%","75%","100%"),each=34))

  comp_final<-as.data.frame(cbind((rbind(power,power,power)),NumbRespColumn,LabResp))
  colnames(comp_final)<-c("power","NumbRespColumn","Response_Rate")


  lg<-data.frame(cbind(power,eff8a,"Large (d=0.8)"));colnames(lg)<-c("Power","Resp","Effect_Size")
  md<-data.frame(cbind(power,eff5a,"Medium (d=0.5)"));colnames(md)<-c("Power","Resp","Effect_Size")
  sm<-data.frame(cbind(power,eff2a,"Small (d=0.2)"));colnames(sm)<-c("Power","Resp","Effect_Size")

  eff_final<-rbind(lg,md,sm)



  #### create ggplot ###

  xlab_chart <- paste("Responses per participant (n =",NumbPart,"participants)" )

  #  ggplot2::scale_x_continuous(limits = c(0,(round((NumbResp+40),-1))),breaks =seq(0, (round(NumbResp+40,-1)), by=20))+
  #round_any(NumbResp, 10, f = ceiling)

  if(NumbResp<=10) {Figure_X_Limit<-10}
  if (NumbResp>10 & NumbResp<=15) {Figure_X_Limit<-15}
  if (NumbResp>15 & NumbResp<=20) {Figure_X_Limit<-20}
  if(NumbResp>20) {Figure_X_Limit<-(plyr::round_any(NumbResp, 10, f = ceiling)+10)}

  if(max(eff_final[(eff_final$Resp<NumbResp & eff_final$Effect_Size=="Large (d=0.8)"),]$Power)==0.99) {
    eff_final<-rbind(eff_final,data.frame(Power=0.99,Resp=NumbResp,Effect_Size="Large (d=0.8)"))}

  if(max(eff_final[(eff_final$Resp<NumbResp & eff_final$Effect_Size=="Medium (d=0.5)"),]$Power)==0.99) {
    eff_final<-rbind(eff_final,data.frame(Power=0.99,Resp=NumbResp,Effect_Size="Medium (d=0.5)"))}



  PowerPlot1<-ggplot2::ggplot()+ ggplot2::geom_line(ggplot2::aes(x = Resp,y = Power,color=Effect_Size),size=1, data=eff_final[eff_final$Resp<=NumbResp,])+
    ggplot2::xlab(xlab_chart) +
    ggplot2::ylab("Power (1-beta)") +
    ggplot2::scale_y_continuous(breaks=c(0,0.2,0.4,0.6,0.8,1.00), limits=c(0.1,1.00))+
    ggplot2::geom_vline(xintercept=(NumbResp*.50),color="grey65", linetype = 3)+
    ggplot2::geom_vline(xintercept=(NumbResp*.75),color="grey65", linetype = 2)+
    ggplot2::scale_x_continuous(limits = c(0,Figure_X_Limit))+
    ggplot2::geom_vline(xintercept=(NumbResp),color="grey65", linetype = 1)+
    ggplot2::geom_line(ggplot2::aes(x = as.numeric(NumbRespColumn), y = as.numeric(power), linetype=Response_Rate), data=comp_final,color="grey65")+
    ggplot2::theme_classic() + ggplot2::scale_linetype(name="Completion rate") +
    ggplot2::scale_color_manual(name="Effect Size",values=c(COL.8,COL.5,COL.2))
  return(PowerPlot1)
}
```

```{r Data}
coping_data_filtered <- read.csv("Created_datasets/Secondary_coping_data_2024_07_12.csv") 
```

```{r MLM power curve}
ema.powercurve(NumbPart = 98, 
               NumbResp = 4, 
               days = 4, 
               respday = 1, 
               Est_ICC = 0.50, 
               COL.8 = "red", COL.5 = "blue", COL.2 = "green" )
```


```{r MLM data prep}
# Participant-mean scores for coping
Coping_data_filtered$SRC_17_pmeans <- pmean(Coping_data_filtered$id,
                                            Coping_data_filtered$srcs17)

# person-centered means coping
Coping_data_filtered$SRC_17_pcent <- pcenter(Coping_data_filtered$id,
                                             Coping_data_filtered$srcs17)

# Intercept only models 
uncon_inq <- lmer(inq ~ 1 + (1 | id), data = Coping_data_filtered)
tab_model(uncon_inq, p.val = "kr") # ICC = .48

uncon_bdi <- lmer(bdi ~ 1 + (1 | id), data = Coping_data_filtered)
tab_model(uncon_bdi, p.val = "kr") # ICC = .49

uncon_bhs <- lmer(bhs ~ 1 + (1 | id), data = Coping_data_filtered)
tab_model(uncon_bhs, p.val = "kr") # ICC = .49

uncon_rls <- lmer(rls ~ 1 + (1 | id), data = Coping_data_filtered)
tab_model(uncon_rls,  p.val = "kr") # ICC = .47
```

```{r MLM with SRC}

##### BDI #####

model_SRC_17_to_BDI <- lmer(
  bdi ~ SRC_17_pmeans # created above
  + SRC_17_pcent      # created above
  + month 
  + (1 | id),
  data = Coping_data_filtered)

(co_1 <- performance::check_outliers(model_SRC_17_to_BDI, method = "all")) # No outliers detected

##### TB #####

model_SRC_17_to_TB <- lmer(
  inq_tb ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + (1 | id),
  data = Coping_data_filtered)

# options(mc.cores = 4)
(co_2 <- performance::check_outliers(model_SRC_17_to_TB, method = "all")) # No outliers detected

##### PB #####

model_SRC_17_to_PB <- lmer(
  inq_pb ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + (1 | id),
  data = Coping_data_filtered)

(co_3 <- performance::check_outliers(model_SRC_17_to_PB, method = "all")) # No outliers detected

##### BHS ###

model_SRC_17_to_BHS <- lmer(
  bhs ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + (1 | id),
  data = Coping_data_filtered)

(co_4 <- performance::check_outliers(model_SRC_17_to_BHS, method = "all")) # No outliers detected

##### RLS #####

model_SRC_17_to_RLS <- lmer(
  rls ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + (1 | id),
  data = Coping_data_filtered)

(co_5 <- performance::check_outliers(model_SRC_17_to_RLS, method = "all")) # No outliers detected

#### Tables ####

tab_model(model_SRC_17_to_BHS, model_SRC_17_to_BDI,
          show.se = FALSE, show.std = TRUE, show.stat = FALSE,  p.val = "kr", show.df = FALSE, p.style = "stars")

tab_model(model_SRC_17_to_RLS,
          show.se = FALSE, show.std = TRUE, show.stat = FALSE,  p.val = "kr", show.df = FALSE, p.style = "stars")

tab_model(model_SRC_17_to_PB, model_SRC_17_to_TB,
          show.se = FALSE, show.std = TRUE, show.stat = FALSE,  p.val = "kr", show.df = FALSE, p.style = "stars")

#### Cohen's d (--power) ####

lme.dscore(model_SRC_17_to_RLS, data = Coping_data_filtered, type = "lme4") 
lme.dscore(model_SRC_17_to_BDI, data = Coping_data_filtered, type = "lme4") 
lme.dscore(model_SRC_17_to_BHS, data = Coping_data_filtered, type = "lme4") 
lme.dscore(model_SRC_17_to_PB, data = Coping_data_filtered, type = "lme4")
lme.dscore(model_SRC_17_to_TB, data = Coping_data_filtered, type = "lme4")
```

