---
title: "03b_main_analysis_sensitivity"
output: github_document
keep_html: TRUE
---

# NOTE: this script assumed 03a has been run and those functions/objects have been created.

```{r Packages}

if (!require("bigutilsr")) {install.packages("bigutilsr"); require("bigutilsr")}
if (!require("dbscan")) {install.packages("dbscan"); require("dbscan")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("EMAtools")) {install.packages("EMAtools"); require("EMAtools")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("ggstatsplot")) {install.packages("ggstatsplot"); require("ggstatsplot")}
if (!require("ICS")) {install.packages("ICS"); require("ICS")}
if (!require("ICSOutlier")) {install.packages("ICSOutlier"); require("ICSOutlier")}
if (!require("insight")) {install.packages("insight"); require("insight")}
if (!require("lme4")) {install.packages("lme4"); require("lme4")}
if (!require("lmerTest")) {install.packages("lmerTest"); require("lmerTest")}
if (!require("performance")) {install.packages("performance"); require("performance")}
if (!require("psych")) {install.packages("psych"); require("psych")}
if (!require("pwr")) {install.packages("pwr"); require("pwr")}
if (!require("sjPlot")) {install.packages("sjPlot"); require("sjPlot")}
devtools::install_github("sjPlot/sjstats")
if (!require("sjstats")) {install.packages("sjstats"); require("sjstats")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")}
```

```{r Data}
coping_data_filtered <- read.csv("Created_datasets/Secondary_coping_data_2024_07_12.csv") 
```

# main sensitivity analysis 1 - total SRC adjusted for SI; tables from this script are in supplement 4.
```{r MLM main models with SI}

# Participant-mean scores for coping
Coping_data_filtered$SRC_17_pmeans <- pmean(Coping_data_filtered$id,
                                            Coping_data_filtered$srcs17)

# person-centered means coping
Coping_data_filtered$SRC_17_pcent <- pcenter(Coping_data_filtered$id,
                                             Coping_data_filtered$srcs17)
                                             
##### BDI #####

model_SI_SRC_17_to_BDI <- lmer(
  bdi ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered)

(co_1 <- performance::check_outliers(model_SI_SRC_17_to_BDI, method = "all")) # 1 outlier detected: case 200
outlier_indices <- which(co_1)
insight::get_data(model_SI_SRC_17_to_BDI)[outlier_indices, ] # BX-162 month 6

# Remove outlier 
Coping_data_filtered_co_1 <- Coping_data_filtered[!(Coping_data_filtered$id == "BX-162" 
                                               & Coping_data_filtered$month == 6), ]

model_SI_SRC_17_to_BDI <- lmer(
  bdi ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered_co_1)

(co_1 <- performance::check_outliers(model_SI_SRC_17_to_BDI, method = "all")) # 1 outlier detected: case 24
outlier_indices <- which(co_1)
insight::get_data(model_SI_SRC_17_to_BDI)[outlier_indices, ] # BX-162 month 6

# Remove outlier 
Coping_data_filtered_co_1 <- Coping_data_filtered_co_1[!(Coping_data_filtered_co_1$id == "BX-035" 
                                                         & Coping_data_filtered_co_1$month == 0), ]

model_SI_SRC_17_to_BDI <- lmer(
  bdi ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered_co_1)

(co_1 <- performance::check_outliers(model_SI_SRC_17_to_BDI, method = "all")) # OK: No outliers detected.

##### INQ #####

model_SI_SRC_17_to_INQ <- lmer(
  inq ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered)

(co_2 <- performance::check_outliers(model_SI_SRC_17_to_INQ, method = "all")) # 1 outlier detected: case 200
outlier_indices <- which(co_2)
insight::get_data(model_SI_SRC_17_to_INQ)[outlier_indices, ] # BX-035 month 0

# Remove outlier 
Coping_data_filtered_co_2 <- Coping_data_filtered[!(Coping_data_filtered$id == "BX-035" &
                                                     (Coping_data_filtered$month == 0 |
                                                      Coping_data_filtered$month == 3)), 
                                                  # & month 3 - after another round of outlier removal
                                                  ]

model_SI_SRC_17_to_INQ <- lmer(
  inq ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered_co_2)

(co_2 <- performance::check_outliers(model_SI_SRC_17_to_INQ, method = "all")) 
outlier_indices <- which(co_2)
insight::get_data(model_SI_SRC_17_to_INQ)[outlier_indices, ] # BX-106 month 12

# Remove outlier 
Coping_data_filtered_co_2 <- Coping_data_filtered_co_2[!(Coping_data_filtered_co_2$id == "BX-106" 
                                                         & Coping_data_filtered_co_2$month == 12), ] 
# no outliers detected after that

###### PB ######

model_SI_SRC_17_to_PB <- lmer(
  inq_pb ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered)

(co_2 <- performance::check_outliers(model_SI_SRC_17_to_PB, method = "all")) # 1 outlier detected: case 54
outlier_indices <- which(co_2)
insight::get_data(model_SI_SRC_17_to_PB)[outlier_indices, ] # BX-035 month 0

# Remove outlier 
Coping_data_filtered_co_2 <- Coping_data_filtered[!(Coping_data_filtered$id == "BX-035" & Coping_data_filtered$month == 0),]

model_SI_SRC_17_to_PB <- lmer(
  inq_pb ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered_co_2)

(co_2 <- performance::check_outliers(model_SI_SRC_17_to_PB, method = "all")) 
outlier_indices <- which(co_2)
insight::get_data(model_SI_SRC_17_to_PB)[outlier_indices, ] # BX-034 month 0 

# Remove outlier 
Coping_data_filtered_co_3 <- Coping_data_filtered_co_2[!(Coping_data_filtered_co_2$id == "BX-034" 
                                                         & Coping_data_filtered_co_2$month == 0),]

model_SI_SRC_17_to_PB <- lmer(
  inq_pb ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered_co_3)

(co_3 <- performance::check_outliers(model_SI_SRC_17_to_PB, method = "all")) 
outlier_indices <- which(co_3) # none

###### TB ######

model_SI_SRC_17_to_TB <- lmer(
  inq_tb ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered)

(co_2 <- performance::check_outliers(model_SI_SRC_17_to_TB, method = "all")) # 1 outlier detected: case 54
outlier_indices <- which(co_2)
insight::get_data(model_SI_SRC_17_to_TB)[outlier_indices, ] # BX-106 month 12

# Remove outlier 
Coping_data_filtered_co_2 <- Coping_data_filtered[!(Coping_data_filtered$id == "BX-106" 
                                                    & Coping_data_filtered$month == 12),]

model_SI_SRC_17_to_TB <- lmer(
  inq_tb ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered_co_2)

(co_2 <- performance::check_outliers(model_SI_SRC_17_to_TB, method = "all")) # 1 outlier detected: case 54
outlier_indices <- which(co_2)
insight::get_data(model_SI_SRC_17_to_TB)[outlier_indices, ] # no more

##### BHS ####

model_SI_SRC_17_to_BHS <- lmer(
  bhs ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered)

(co_3 <- performance::check_outliers(model_SI_SRC_17_to_BHS, method = "all")) # 2 outliers detected: cases 26, 54.
outlier_indices <- which(co_3)
insight::get_data(model_SI_SRC_17_to_BHS)[outlier_indices, ] # BX-035 month 0 and BX-014 month 6

Coping_data_filtered_co_3 <- Coping_data_filtered[!(
  (Coping_data_filtered$id == "BX-035" & Coping_data_filtered$month == 0) |
  (Coping_data_filtered$id == "BX-014" & Coping_data_filtered$month == 6)
), ]

model_SI_SRC_17_to_BHS <- lmer(
  bhs ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered_co_3)

(co_3 <- performance::check_outliers(model_SI_SRC_17_to_BHS, method = "all")) # No outliers detected.

##### RLS #####

model_SI_SRC_17_to_RLS <- lmer(
  rls ~ SRC_17_pmeans 
  + SRC_17_pcent 
  + month 
  + ssi
  + (1 | id),
  data = Coping_data_filtered)

(co_4 <- performance::check_outliers(model_SI_SRC_17_to_RLS, method = "all")) # No outliers detected

#### Tables ####

tab_model(model_SI_SRC_17_to_BHS, model_SI_SRC_17_to_BDI,
          show.se = FALSE, show.std = TRUE, show.stat = FALSE,  p.val = "kr", show.df = FALSE, p.style = "stars")

tab_model(model_SI_SRC_17_to_TB, model_SI_SRC_17_to_PB,
          show.se = FALSE, show.std = TRUE, show.stat = FALSE,  p.val = "kr", show.df = FALSE, p.style = "stars")

tab_model(model_SI_SRC_17_to_RLS,
          show.se = FALSE, show.std = TRUE, show.stat = FALSE,  p.val = "kr", show.df = FALSE, p.style = "stars")

#### Cohen's d (--power) ####

lme.dscore(model_SI_SRC_17_to_RLS, data = Coping_data_filtered, type = "lme4") 
lme.dscore(model_SI_SRC_17_to_BDI, data = Coping_data_filtered, type = "lme4") 
lme.dscore(model_SI_SRC_17_to_BHS, data = Coping_data_filtered, type = "lme4") 
lme.dscore(model_SI_SRC_17_to_PB, data = Coping_data_filtered, type = "lme4")
lme.dscore(model_SI_SRC_17_to_TB, data = Coping_data_filtered, type = "lme4")
```

# main sensitivity analysis 2 - RCT group differences
```{r Tx condition comparisons}
(arm_comparison_SRC <- ggwithinstats(
  data = Coping_data_filtered,
  x = arm_rec,
  y = srcs17,
  type = "np",
  effsize.type = "d",
  conf.level = 0.95,
  title = "",
  xlab = "Treatment condition",
  ylab = "Suicide-related coping",
  package = "ggsci",
  palette = "nrc_npg"))

(arm_comparison_INQ <- ggwithinstats(
  data = Coping_data_filtered,
  x = arm_rec,
  y = inq,
  type = "np",
  effsize.type = "d",
  conf.level = 0.95,
  title = "",
  xlab = "Treatment condition",
  ylab = "Thwarted interpersonal needs",
  package = "ggsci",
  palette = "nrc_npg"))

(arm_comparison_PB <- ggwithinstats(
  data = Coping_data_filtered,
  x = arm_rec,
  y = inq_pb,
  type = "np",
  effsize.type = "d",
  conf.level = 0.95,
  title = "",
  xlab = "Treatment condition",
  ylab = "Perceived burden",
  package = "ggsci",
  palette = "nrc_npg"))

(arm_comparison_TB <- ggwithinstats(
  data = Coping_data_filtered,
  x = arm_rec,
  y = inq_tb,
  type = "np",
  effsize.type = "d",
  conf.level = 0.95,
  title = "",
  xlab = "Treatment condition",
  ylab = "Thwarted belonging",
  package = "ggsci",
  palette = "nrc_npg"))

(arm_comparison_SSI <- ggwithinstats(
  data = Coping_data_filtered,
  x = arm_rec,
  y = ssi,
  type = "np",
  effsize.type = "d",
  conf.level = 0.95,
  title = "",
  xlab = "Treatment condition",
  ylab = "Suicidal ideation",
  package = "ggsci",
  palette = "nrc_npg"))

(arm_comparison_BHS <- ggwithinstats(
  data = Coping_data_filtered,
  x = arm_rec,
  y = bhs,
  type = "np",
  effsize.type = "d",
  conf.level = 0.95,
  title = "",
  package = "ggsci",
  xlab = "Treatment condition",
  ylab = "Hopelessness",
  palette = "nrc_npg"))

(arm_comparison_BDI <- ggwithinstats(
  data = Coping_data_filtered,
  x = arm_rec,
  y = bdi,
  type = "np",
  effsize.type = "d",
  conf.level = 0.95,
  title = "",
  package = "ggsci",
  xlab = "Treatment condition",
  ylab = "Depression",
  palette = "nrc_npg"))

(arm_comparison_RLS <- ggwithinstats(
  data = Coping_data_filtered,
  x = arm_rec,
  y = rls,
  type = "np",
  effsize.type = "d",
  conf.level = 0.95,
  title = "",
  xlab = "Treatment condition",
  ylab = "Reasons for living",
  package = "ggsci",
  palette = "nrc_npg"))

png("03b_Output/Arm_differences_withinBPD.png")
grid.arrange(arm_comparison_SRC, arm_comparison_INQ,
             arm_comparison_SSI, arm_comparison_BDI, 
             arm_comparison_BHS, arm_comparison_RLS, 
             nrow = 3)
dev.off()

pdf("03b_Output/Arm_differences_withinBPD.pdf", height = 12, width = 11)
grid.arrange(arm_comparison_SRC, arm_comparison_INQ, 
             arm_comparison_PB, arm_comparison_TB,
             arm_comparison_SSI, arm_comparison_BDI, 
             arm_comparison_BHS, arm_comparison_RLS, 
             nrow = 3)
dev.off()
```

