---
title: "04c_supp5"
output: github_document
keep_html: TRUE
---

```{r Packages}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("ggstatsplot")) {install.packages("ggstatsplot"); require("ggstatsplot")}
if (!require("gridExtra")) {install.packages("gridExtra"); require("gridExtra")}
if (!require("psych")) {install.packages("psych"); require("psych")}
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")}
```

```{r Data}
Coping_data_filtered <- read.csv("Created_datasets/Secondary_coping_data_2024_07_12.csv")
```

#1) For R&R, add SRC scaled visualizations over time (*only for those with complete data)
```{r SRC vis/ID}
time_points_summary <- Coping_data_filtered %>%
  dplyr::group_by(id) %>%
  dplyr::summarize(srcs17_timepoints = sum(!is.na(srcs17)))

filtered_data <- time_points_summary[time_points_summary$srcs17_timepoints == 4, ]

participant_dataframes <- list()
plots_list <- list()

for (id_val in unique(filtered_data$id)) {
  
  participant_id <- gsub("^(PH-)", "2-", as.character(id_val))
  participant_id <- gsub("^(BX-)", "1-", participant_id)
  participant_id <- gsub("^(TX-)", "3-", participant_id)
  participant_id <- gsub("^(NP-)", "4-", participant_id)
  
  ID_data_subset <- subset(Coping_data_filtered, id == id_val)
  
  scaled_data <- ID_data_subset %>%
    dplyr::select(month, id, SRC_17_pmeans, srcs17) %>%
    dplyr::mutate(across(c(srcs17), scale))
  
  scaled_data$SRC_17_pmeans_SCALED <- mean(scaled_data$srcs17)
  
  participant_dataframes[[paste0("participant_", id_val, "_data")]] <- scaled_data
  
  p <- ggplot(scaled_data, aes(x = month)) +
    geom_line(aes(y = SRC_17_pmeans_SCALED), color = "black", linetype = "dashed", 
              size = 1.5) +  
    geom_line(aes(y = srcs17), color = "black", size = 2.1) +
    geom_point(aes(y = srcs17), color = "black", size = 3) +  
    labs(title = paste("Participant", participant_id),  
         x = "Wave",
         y = "Values") +
    scale_x_discrete(labels = c("0" = "1", "3" = "2", "6" = "3", "12" = "4")) +  
    theme_minimal() + 
    theme(
      axis.title.x = element_text(size = 20),   
      axis.title.y = element_text(size = 20),   
      axis.text.x = element_text(size = 20),    
      axis.text.y = element_text(size = 20),    
      plot.title = element_text(size = 23, face = "bold", hjust = 0.5), 
      legend.text = element_text(size = 20),    
      legend.title = element_text(size = 20)    
    )
  
  plots_list[[paste0("participant_", id_val)]] <- p
}

pdf("04c_Output/combined_plots.pdf", width = 45, height = 45)
grid.arrange(grobs = plots_list, ncol = 6)  
dev.off()

```

# 2) To accompany #1 and provide more detail on change (across persons) and (in)consistent directionality
```{r SRC person level change}
Coping_data_filtered <- Coping_data_filtered %>%
  left_join(time_points_summary %>% select(id, srcs17_timepoints), by = "id")

Coping_data_filtered_4 <- Coping_data_filtered %>%
  filter(srcs17_timepoints == 4) %>%
  select(id, srcs17, month)

length(unique(Coping_data_filtered_4$id)) # make sure it's the right #

long_df <- Coping_data_filtered_4 %>% pivot_longer(cols = -c(id), 
                                                   names_to = "item", 
                                                   values_to = "answer_id")


long_df <- long_df %>% mutate(answer_id = as.numeric(answer_id))

vars <- c("srcs17")

# calculate individual mean, sd, skew, etc. 
(df_desc <- long_df %>%
  dplyr::filter(item %in% vars) %>%  
  dplyr::group_by(id, item) %>%
  dplyr::summarize(
    imean = mean(answer_id, na.rm = TRUE),
    imed = median(answer_id, na.rm = TRUE),
    isd = sd(answer_id, na.rm = TRUE),
    iskew = moments::skewness(answer_id, na.rm = TRUE),
    irmssd = psych::rmssd(answer_id, na.rm = TRUE)
  ))

# add change scores to above table
Coping_data_filtered_4 <- Coping_data_filtered_4 %>%
  mutate(month = as.character(month))

wide_df <- Coping_data_filtered_4 %>%
  pivot_wider(names_from = month, values_from = srcs17)

# change scores
wide_df <- wide_df %>%
  rename(
    srcs17_0 = `0`,
    srcs17_3 = `3`,
    srcs17_6 = `6`,
    srcs17_12 = `12`
  ) %>%
  mutate(
    change_0_3 = srcs17_3 - srcs17_0,
    change_3_6 = srcs17_6 - srcs17_3,
    change_6_12 = srcs17_12 - srcs17_6,
    change_0_12 = srcs17_12 - srcs17_0
  )

# summay of change 
summary(wide_df$change_0_3)
summary(wide_df$change_3_6)
summary(wide_df$change_6_12)
summary(wide_df$change_0_12)

# direction of consistent change
wide_df_summary <- wide_df %>%
  mutate(
    direction_0_3 = case_when(
      change_0_3 > 0 ~ "positive",
      change_0_3 < 0 ~ "negative",
      TRUE ~ "no_change"
    ),
    direction_3_6 = case_when(
      change_3_6 > 0 ~ "positive",
      change_3_6 < 0 ~ "negative",
      TRUE ~ "no_change"
    ),
    direction_6_12 = case_when(
      change_6_12 > 0 ~ "positive",
      change_6_12 < 0 ~ "negative",
      TRUE ~ "no_change"
    )
  ) %>%
  mutate(
    overall_direction = case_when(
      direction_0_3 == "positive" 
      & direction_3_6 == "positive" 
      & direction_6_12 == "positive" ~ "all_positive",
      direction_0_3 == "negative" 
      & direction_3_6 == "negative"
      & direction_6_12 == "negative" ~ "all_negative",
      TRUE ~ "mixed"
    )
  ) %>%
  summarise(
    all_positive = sum(overall_direction == "all_positive", na.rm = TRUE),
    all_negative = sum(overall_direction == "all_negative", na.rm = TRUE),
    mixed = sum(overall_direction == "mixed", na.rm = TRUE)
  )

# add change scores to the table
df_desc_changes <- df_desc %>%
  left_join(wide_df, by = "id")

# change id column to match the visualization and remove raw
df_desc_changes <- df_desc_changes %>%
  mutate(
    id = gsub("^(PH-)", "2-", as.character(id)),
    id = gsub("^(BX-)", "1-", id),
    id = gsub("^(TX-)", "3-", id),
    id = gsub("^(NP-)", "4-", id)
  ) %>%
  select(-srcs17_0, -srcs17_3, -srcs17_6, -srcs17_12)  

write.csv(df_desc_changes, paste0("04c_Output/RR_SRC_descriptives_SG_", Sys.Date(), ".csv")) 
```

